apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: myenv
            - secretRef:
                name: mysecret-site
          readinessProbe:
            httpGet:
              path: /healthz # Replace with your application's actual readiness path
              port: 80
          livenessProbe:
            httpGet:
              path: / # Replace with your application's actual readiness path
              port: 80
          restartPolicy: always
          volumes:
            - name: data-volume
              hostPath:
              path: /data
              type: Directory

        - name: log-container
          image: busybox
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          command: ["/bin/bash"]
          arg:
            [
              "-c",
              "while true; do echo $(date) - Log from log-container; sleep 10; done",
            ]
          restartPolicy: always
