apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  completions: 3
  parallelism: 3
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: pi
          image: ubuntu
          command: ["expr", "3", ‘+', ‘2’]
      restartPolicy: Never
